name: Build Zed LLM Server

on:
  push:
    branches:
      - zed_llm_server
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Enable long paths in Git
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Install PSToml module
        shell: pwsh
        run: Install-Module -Name PSToml -Scope CurrentUser -Force

      - name: Checkout self (workflow repo)
        uses: actions/checkout@v4

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: llm-server-windows-${{ hashFiles('Cargo.lock') }}
          workspaces: ". -> target"

      - name: Build zed_llm_server release
        run: cargo build --release --package zed_llm_server

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: zed-llm-server-release
          path: target/release/zed_llm_server.exe

  build_linux:
    runs-on: buildjet-16vcpu-ubuntu-2204

    steps:
      - name: Checkout self (workflow repo)
        uses: actions/checkout@v4

      - name: Add Rust to the PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Linux dependencies
        run: ./script/linux

      - name: Limit target directory size
        run: script/clear-target-dir-if-larger-than 100

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: llm-server-linux-${{ hashFiles('Cargo.lock') }}
          workspaces: ". -> target"

      - name: Build zed_llm_server release
        run: cargo build --release --package zed_llm_server

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: zed-llm-server-linux-release
          path: target/release/zed_llm_server

  build_mac:
    runs-on: macos-latest

    steps:
      - name: Checkout self (workflow repo)
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

      - name: Accept Xcode license
        run: sudo xcodebuild -license accept

      - name: Install Homebrew dependencies
        run: brew update && brew install cmake

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: llm-server-macos-${{ hashFiles('Cargo.lock') }}
          workspaces: ". -> target"

      - name: Build zed_llm_server release
        run: cargo build --release --package zed_llm_server

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: zed-llm-server-macos-release
          path: target/release/zed_llm_server
